package entities;
// Generated 05-07-2017 11:24:52 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Drafts generated by hbm2java
 */
public class Drafts  implements java.io.Serializable {


     private BigDecimal id;
     private Date date;
     private BigDecimal number1;
     private BigDecimal number2;
     private BigDecimal number3;
     private BigDecimal number4;
     private BigDecimal number5;
     private BigDecimal number6;
     private Set ticketses = new HashSet(0);
     private Set winnerses = new HashSet(0);

    public Drafts() {
    }

	
    public Drafts(BigDecimal id, Date date, BigDecimal number1, BigDecimal number2, BigDecimal number3, BigDecimal number4, BigDecimal number5, BigDecimal number6) {
        this.id = id;
        this.date = date;
        this.number1 = number1;
        this.number2 = number2;
        this.number3 = number3;
        this.number4 = number4;
        this.number5 = number5;
        this.number6 = number6;
    }
    public Drafts(BigDecimal id, Date date, BigDecimal number1, BigDecimal number2, BigDecimal number3, BigDecimal number4, BigDecimal number5, BigDecimal number6, Set ticketses, Set winnerses) {
       this.id = id;
       this.date = date;
       this.number1 = number1;
       this.number2 = number2;
       this.number3 = number3;
       this.number4 = number4;
       this.number5 = number5;
       this.number6 = number6;
       this.ticketses = ticketses;
       this.winnerses = winnerses;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public BigDecimal getNumber1() {
        return this.number1;
    }
    
    public void setNumber1(BigDecimal number1) {
        this.number1 = number1;
    }
    public BigDecimal getNumber2() {
        return this.number2;
    }
    
    public void setNumber2(BigDecimal number2) {
        this.number2 = number2;
    }
    public BigDecimal getNumber3() {
        return this.number3;
    }
    
    public void setNumber3(BigDecimal number3) {
        this.number3 = number3;
    }
    public BigDecimal getNumber4() {
        return this.number4;
    }
    
    public void setNumber4(BigDecimal number4) {
        this.number4 = number4;
    }
    public BigDecimal getNumber5() {
        return this.number5;
    }
    
    public void setNumber5(BigDecimal number5) {
        this.number5 = number5;
    }
    public BigDecimal getNumber6() {
        return this.number6;
    }
    
    public void setNumber6(BigDecimal number6) {
        this.number6 = number6;
    }
    public Set getTicketses() {
        return this.ticketses;
    }
    
    public void setTicketses(Set ticketses) {
        this.ticketses = ticketses;
    }
    public Set getWinnerses() {
        return this.winnerses;
    }
    
    public void setWinnerses(Set winnerses) {
        this.winnerses = winnerses;
    }




}


