package entities;
// Generated 25-jun-2017 14:24:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Profiles generated by hbm2java
 */
public class Profiles  implements java.io.Serializable {


     private BigDecimal id;
     private String name;
     private Set userses = new HashSet(0);
     private Set profilesPageses = new HashSet(0);

    public Profiles() {
    }

	
    public Profiles(BigDecimal id, String name) {
        this.id = id;
        this.name = name;
    }
    public Profiles(BigDecimal id, String name, Set userses, Set profilesPageses) {
       this.id = id;
       this.name = name;
       this.userses = userses;
       this.profilesPageses = profilesPageses;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }
    public Set getProfilesPageses() {
        return this.profilesPageses;
    }
    
    public void setProfilesPageses(Set profilesPageses) {
        this.profilesPageses = profilesPageses;
    }




}


