package entities;
// Generated 05-jul-2017 1:22:33 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ProfilesPages generated by hbm2java
 */
public class ProfilesPages  implements java.io.Serializable {


     private BigDecimal id;
     private Pages pages;
     private Profiles profiles;

    public ProfilesPages() {
    }

    public ProfilesPages(BigDecimal id, Pages pages, Profiles profiles) {
       this.id = id;
       this.pages = pages;
       this.profiles = profiles;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Pages getPages() {
        return this.pages;
    }
    
    public void setPages(Pages pages) {
        this.pages = pages;
    }
    public Profiles getProfiles() {
        return this.profiles;
    }
    
    public void setProfiles(Profiles profiles) {
        this.profiles = profiles;
    }




}


