package entities;
// Generated 25-jun-2017 14:24:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Recharges generated by hbm2java
 */
public class Recharges  implements java.io.Serializable {


     private BigDecimal id;
     private Users users;
     private BigDecimal amount;
     private BigDecimal transactionsId;

    public Recharges() {
    }

    public Recharges(BigDecimal id, Users users, BigDecimal amount, BigDecimal transactionsId) {
       this.id = id;
       this.users = users;
       this.amount = amount;
       this.transactionsId = transactionsId;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public BigDecimal getTransactionsId() {
        return this.transactionsId;
    }
    
    public void setTransactionsId(BigDecimal transactionsId) {
        this.transactionsId = transactionsId;
    }




}


