package entities;
// Generated 05-jul-2017 1:22:33 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Transactions generated by hbm2java
 */
public class Transactions  implements java.io.Serializable {


     private BigDecimal id;
     private String paymentMethod;
     private BigDecimal amount;
     private Set rechargeses = new HashSet(0);
     private Set payments = new HashSet(0);

    public Transactions() {
    }

	
    public Transactions(BigDecimal id, String paymentMethod, BigDecimal amount) {
        this.id = id;
        this.paymentMethod = paymentMethod;
        this.amount = amount;
    }
    public Transactions(BigDecimal id, String paymentMethod, BigDecimal amount, Set rechargeses, Set payments) {
       this.id = id;
       this.paymentMethod = paymentMethod;
       this.amount = amount;
       this.rechargeses = rechargeses;
       this.payments = payments;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public Set getRechargeses() {
        return this.rechargeses;
    }
    
    public void setRechargeses(Set rechargeses) {
        this.rechargeses = rechargeses;
    }
    public Set getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set payments) {
        this.payments = payments;
    }




}


