package entities;
// Generated 07-07-2017 11:51:38 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Transactions generated by hbm2java
 */
public class Transactions  implements java.io.Serializable {


     private BigDecimal id;
     private String paymentMethod;
     private BigDecimal amount;
     private Set rechargeses = new HashSet(0);

    public Transactions() {
    }

	
    public Transactions(BigDecimal id, String paymentMethod, BigDecimal amount) {
        this.id = id;
        this.paymentMethod = paymentMethod;
        this.amount = amount;
    }
    public Transactions(BigDecimal id, String paymentMethod, BigDecimal amount, Set rechargeses) {
       this.id = id;
       this.paymentMethod = paymentMethod;
       this.amount = amount;
       this.rechargeses = rechargeses;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public Set getRechargeses() {
        return this.rechargeses;
    }
    
    public void setRechargeses(Set rechargeses) {
        this.rechargeses = rechargeses;
    }


    @Override
    public String toString() {
        return "{\"data\": {" + 
                "\"id\": \"" + id.intValueExact() + '"' +
                ",\"paymentMethod\": \"" + paymentMethod + '"' +
                ",\"amount\": \"" + amount + '"' +
                "}}";
    }


}


