package entities;
// Generated 25-jun-2017 14:24:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private BigDecimal id;
     private Profiles profiles;
     private String username;
     private String password;
     private String firstName;
     private String lastName;
     private BigDecimal wallet;
     private Set winnerses = new HashSet(0);
     private Set rechargeses = new HashSet(0);
     private Set ticketses = new HashSet(0);

    public Users() {
    }

	
    public Users(BigDecimal id, Profiles profiles, String username, String password, String firstName, String lastName, BigDecimal wallet) {
        this.id = id;
        this.profiles = profiles;
        this.username = username;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.wallet = wallet;
    }
    public Users(BigDecimal id, Profiles profiles, String username, String password, String firstName, String lastName, BigDecimal wallet, Set winnerses, Set rechargeses, Set ticketses) {
       this.id = id;
       this.profiles = profiles;
       this.username = username;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.wallet = wallet;
       this.winnerses = winnerses;
       this.rechargeses = rechargeses;
       this.ticketses = ticketses;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Profiles getProfiles() {
        return this.profiles;
    }
    
    public void setProfiles(Profiles profiles) {
        this.profiles = profiles;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public BigDecimal getWallet() {
        return this.wallet;
    }
    
    public void setWallet(BigDecimal wallet) {
        this.wallet = wallet;
    }
    public Set getWinnerses() {
        return this.winnerses;
    }
    
    public void setWinnerses(Set winnerses) {
        this.winnerses = winnerses;
    }
    public Set getRechargeses() {
        return this.rechargeses;
    }
    
    public void setRechargeses(Set rechargeses) {
        this.rechargeses = rechargeses;
    }
    public Set getTicketses() {
        return this.ticketses;
    }
    
    public void setTicketses(Set ticketses) {
        this.ticketses = ticketses;
    }




}


